### ISSUE TITLE
Error parsing object[] array type

### ISSUE THREAD

**Issue by slavb18** [brettz9/jsdoc-jsonschema#2]
Hi!

I have example schema:

```javascript
jsdocToJsonSchema(`

/** @typedef {object} json
 * @property {number} productId
 * @property {string} buyerUid
 * @property {object} data
 * @property {string} data.name
 * @property {string} data.dealId
 * @property {string} data.status
 * @property {string} data.stepId
 * @property {object[]} data.estimate
 * @property {string} data.estimate.task
 * @property {number} data.estimate.price
 * @property {number} data.totalPrice
 * @property {string} data.description
 * @property {string} data.accountNumber
 * @property {string} data.deadlineExecution
 * @property {string} data.codeVerifyCreatedDate
 * @property {string} endDate
 * @property {boolean} update
 * @property {string} stateCode
 */

`);
```

This code throws Exception:

```
TypeError: properties.push is not a function. (In 'properties.push(property)', 'properties.push' is undefined)
      at handleType (/home/slavb18/work/jsdocschematest/node_modules/jsdoc-jsonschema/src/index.js:420:10)
```

With this syntax (note estimate[])

```
 * @property {object[]} data.estimate
 * @property {string} data.estimate[].task
 * @property {number} data.estimate[].price
```

I got 
TypeError: undefined is not an object (evaluating 'schema.type')
      at /home/slavb18/work/jsdocschematest/node_modules/jsdoc-jsonschema/src/index.js:447:15

How to correctly describe array of objects ?

**Comment by brettz9** [comment]
I'm sorry, but I'm no longer really maintaining this project. I'd accept PRs, but the project as it is doesn't handle too many cases. It's more of utility for something like documenting a CLI with simple types.

Also, the internal parser, jsdoctypeparser has been superseded by jsdoc-type-pratt-parser (which handles more TypeScript types) so any significant revisioning would probably want to switch to that (if not to TypeScript's own).
